/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as PromotionalOffersRouteImport } from './routes/promotional-offers'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as CarsIndexRouteImport } from './routes/cars/index'
import { Route as CarsSlugRouteImport } from './routes/cars/$slug'
import { Route as CarsPrintRouteImport } from './routes/cars/print'
import { Route as OffersIndexRouteImport } from './routes/offers/index'
import { Route as OffersSlugRouteImport } from './routes/offers/$slug'
import { Route as PurchaseIndexRouteImport } from './routes/purchase/index'
import { Route as PurchaseCompaniesRouteImport } from './routes/purchase/companies'
import { Route as PurchaseCustomersRouteImport } from './routes/purchase/customers'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const PromotionalOffersRoute = PromotionalOffersRouteImport.update({
  id: '/promotional-offers',
  path: '/promotional-offers',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsIndexRoute = CarsIndexRouteImport.update({
  id: '/cars/',
  path: '/cars/',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsSlugRoute = CarsSlugRouteImport.update({
  id: '/cars/$slug',
  path: '/cars/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsPrintRoute = CarsPrintRouteImport.update({
  id: '/cars/print',
  path: '/cars/print',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersIndexRoute = OffersIndexRouteImport.update({
  id: '/offers/',
  path: '/offers/',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersSlugRoute = OffersSlugRouteImport.update({
  id: '/offers/$slug',
  path: '/offers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseIndexRoute = PurchaseIndexRouteImport.update({
  id: '/purchase/',
  path: '/purchase/',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseCompaniesRoute = PurchaseCompaniesRouteImport.update({
  id: '/purchase/companies',
  path: '/purchase/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseCustomersRoute = PurchaseCustomersRouteImport.update({
  id: '/purchase/customers',
  path: '/purchase/customers',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/promotional-offers': typeof PromotionalOffersRoute
  '/services': typeof ServicesRoute
  '/cars/$slug': typeof CarsSlugRoute
  '/cars/print': typeof CarsPrintRoute
  '/offers/$slug': typeof OffersSlugRoute
  '/purchase/companies': typeof PurchaseCompaniesRoute
  '/purchase/customers': typeof PurchaseCustomersRoute
  '/cars/': typeof CarsIndexRoute
  '/offers/': typeof OffersIndexRoute
  '/purchase/': typeof PurchaseIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/promotional-offers': typeof PromotionalOffersRoute
  '/services': typeof ServicesRoute
  '/cars/$slug': typeof CarsSlugRoute
  '/cars/print': typeof CarsPrintRoute
  '/offers/$slug': typeof OffersSlugRoute
  '/purchase/companies': typeof PurchaseCompaniesRoute
  '/purchase/customers': typeof PurchaseCustomersRoute
  '/cars': typeof CarsIndexRoute
  '/offers': typeof OffersIndexRoute
  '/purchase': typeof PurchaseIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/promotional-offers': typeof PromotionalOffersRoute
  '/services': typeof ServicesRoute
  '/cars/$slug': typeof CarsSlugRoute
  '/cars/print': typeof CarsPrintRoute
  '/offers/$slug': typeof OffersSlugRoute
  '/purchase/companies': typeof PurchaseCompaniesRoute
  '/purchase/customers': typeof PurchaseCustomersRoute
  '/cars/': typeof CarsIndexRoute
  '/offers/': typeof OffersIndexRoute
  '/purchase/': typeof PurchaseIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/promotional-offers'
    | '/services'
    | '/cars/$slug'
    | '/cars/print'
    | '/offers/$slug'
    | '/purchase/companies'
    | '/purchase/customers'
    | '/cars/'
    | '/offers/'
    | '/purchase/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/promotional-offers'
    | '/services'
    | '/cars/$slug'
    | '/cars/print'
    | '/offers/$slug'
    | '/purchase/companies'
    | '/purchase/customers'
    | '/cars'
    | '/offers'
    | '/purchase'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/promotional-offers'
    | '/services'
    | '/cars/$slug'
    | '/cars/print'
    | '/offers/$slug'
    | '/purchase/companies'
    | '/purchase/customers'
    | '/cars/'
    | '/offers/'
    | '/purchase/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  PromotionalOffersRoute: typeof PromotionalOffersRoute
  ServicesRoute: typeof ServicesRoute
  CarsSlugRoute: typeof CarsSlugRoute
  CarsPrintRoute: typeof CarsPrintRoute
  OffersSlugRoute: typeof OffersSlugRoute
  PurchaseCompaniesRoute: typeof PurchaseCompaniesRoute
  PurchaseCustomersRoute: typeof PurchaseCustomersRoute
  CarsIndexRoute: typeof CarsIndexRoute
  OffersIndexRoute: typeof OffersIndexRoute
  PurchaseIndexRoute: typeof PurchaseIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promotional-offers': {
      id: '/promotional-offers'
      path: '/promotional-offers'
      fullPath: '/promotional-offers'
      preLoaderRoute: typeof PromotionalOffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars/': {
      id: '/cars/'
      path: '/cars'
      fullPath: '/cars/'
      preLoaderRoute: typeof CarsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars/$slug': {
      id: '/cars/$slug'
      path: '/cars/$slug'
      fullPath: '/cars/$slug'
      preLoaderRoute: typeof CarsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars/print': {
      id: '/cars/print'
      path: '/cars/print'
      fullPath: '/cars/print'
      preLoaderRoute: typeof CarsPrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers/': {
      id: '/offers/'
      path: '/offers'
      fullPath: '/offers/'
      preLoaderRoute: typeof OffersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers/$slug': {
      id: '/offers/$slug'
      path: '/offers/$slug'
      fullPath: '/offers/$slug'
      preLoaderRoute: typeof OffersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase/': {
      id: '/purchase/'
      path: '/purchase'
      fullPath: '/purchase/'
      preLoaderRoute: typeof PurchaseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase/companies': {
      id: '/purchase/companies'
      path: '/purchase/companies'
      fullPath: '/purchase/companies'
      preLoaderRoute: typeof PurchaseCompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase/customers': {
      id: '/purchase/customers'
      path: '/purchase/customers'
      fullPath: '/purchase/customers'
      preLoaderRoute: typeof PurchaseCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  PromotionalOffersRoute: PromotionalOffersRoute,
  ServicesRoute: ServicesRoute,
  CarsSlugRoute: CarsSlugRoute,
  CarsPrintRoute: CarsPrintRoute,
  OffersSlugRoute: OffersSlugRoute,
  PurchaseCompaniesRoute: PurchaseCompaniesRoute,
  PurchaseCustomersRoute: PurchaseCustomersRoute,
  CarsIndexRoute: CarsIndexRoute,
  OffersIndexRoute: OffersIndexRoute,
  PurchaseIndexRoute: PurchaseIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
